
resolver: lts-16.16

packages:
- BookSamples/CH03/Section3p1
- BookSamples/CH03/Section3p2
- BookSamples/CH03/Section3p3
- BookSamples/CH04/Section4p1
- BookSamples/CH04/Section4p2
- BookSamples/CH05/Section5p1
- BookSamples/CH05/Section5p2p2
- BookSamples/CH05/Section5p2p3
- BookSamples/CH05/Section5p3
- BookSamples/CH06/Section6p1p1
- BookSamples/CH06/Section6p1p2
- BookSamples/CH06/Section6p2
- BookSamples/CH07/Section7p1
- BookSamples/CH07/Section7p2p1
- BookSamples/CH07/Section7p2p2
- BookSamples/CH07/Section7p2p3
