name:                AbstractingOverSTM
version:             0.1.0.0
github:              "githubuser/AbstractingOverSTM"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AbstractingOverSTM#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- mtl
- free
- text
- stm
- containers
- random

library:
  source-dirs: src

executables:
  AbstractingOverSTM-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AbstractingOverSTM

tests:
  AbstractingOverSTM-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AbstractingOverSTM
